from src.backtesting.backtest_engine import Backtest
from src.backtesting.data_fetcher import HistoricalDataFetcher
from src.backtesting.strategy_adapters import adapt_hhhl_strategy, adapt_candlestick_strategy, combined_strategy